# Generated by Django 6.0.4 on 2026-04-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="test",
            new_name="text",
        ),
    ]
