# Generated by Django 6.0.4 on 2026-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article",
            field=models.TextField(max_length=2047),
        ),
    ]
